#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
DEV_CERT="AngryKeyboard Dev"
PROD_CERT="AngryKeyboard Production"

# _valid_identity NAME succeeds when a usable code signing identity is present.
_valid_identity() {
  local out
  out="$(security find-identity -v -p codesigning 2>/dev/null || true)"
  grep -qF "$1" <<< "$out"
}

# _guide_trust NAME tells the human how to mark a fresh certificate trusted,
# which codesign needs before it will use a self-signed identity.
_guide_trust() {
  note "If $1 is missing, mark it trusted:"
  step "Double-click the $1 certificate in Keychain Access."
  step "Expand Trust, set 'When using this certificate' to 'Always Trust'."
  step "Close the window and enter your password when asked."
}

banner "AngryKeyboard channel signing setup"

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "Check prerequisites"
say "This wizard creates one self-signed certificate per channel, points Debug"
say "and Release at them, exports production for CI, and stores the repository"
say "secrets and variable the release workflow reads."
note "It only writes ${DIM}Config/*.local.xcconfig${RESET} into the repo, and those are gitignored."

say ""
say "Checking tools..."
for tool in security openssl xcodebuild; do
  if command -v "$tool" >/dev/null 2>&1; then
    note "found $tool"
  else
    warn "missing $tool, which later stages need"
  fi
done
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  note "gh is authenticated"
else
  warn "gh is missing or unauthenticated; secrets will be skipped, not printed"
fi

if [[ -f "$ROOT/Config/Debug.local.xcconfig" || -f "$ROOT/Config/Release.local.xcconfig" ]]; then
  warn "local signing config already exists and stage 4 will overwrite it"
  if ! confirm "Overwrite Config/*.local.xcconfig?"; then
    say "Stopped before changing anything. Existing files are untouched."
    exit 0
  fi
fi
pause "Press Enter to create the dev certificate."

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "Create and trust the dev certificate"
say "The dev channel signs with its own certificate so a rebuilt app keeps the"
say "same identity and its Input Monitoring grant."
say ""
step "Keychain Access opens in a moment. If it is already open, switch to it."
step "Choose Keychain Access > Certificate Assistant > Create a Certificate."
step "Name: $DEV_CERT"
step "Identity Type: Self-Signed Root"
step "Certificate Type: Code Signing"
step "Tick 'Let me override defaults' to reach Validity Period."
step "Validity Period: 3650 days (the default is 365)."
step "Continue, then Done."
open -a "Keychain Access" >/dev/null 2>&1 || warn "open Keychain Access yourself"
pause "Press Enter once the $DEV_CERT certificate exists."

if _valid_identity "$DEV_CERT"; then
  say "Found a valid code signing identity named $DEV_CERT."
else
  warn "$DEV_CERT is not yet a valid code signing identity."
  _guide_trust "$DEV_CERT"
  pause "Press Enter once you've set it to Always Trust."
  _valid_identity "$DEV_CERT" && say "Identity is now valid." || warn "Still not valid; you can continue and fix it later."
fi

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "Create and trust the production certificate"
say "Production is the identity every release and every recipient's Input"
say "Monitoring grant key to, so its private key gets backed up in a later stage."
say ""
step "Back in Keychain Access: Certificate Assistant > Create a Certificate."
step "Name: $PROD_CERT"
step "Identity Type: Self-Signed Root"
step "Certificate Type: Code Signing"
step "Tick 'Let me override defaults' and set Validity Period to 3650 days."
step "Continue, then Done."
note "On another Mac with the backed-up .p12, import it instead: Keychain Access"
note "> File > Import Items. The wizard detects an existing identity and moves on."
pause "Press Enter once the $PROD_CERT certificate exists."

if _valid_identity "$PROD_CERT"; then
  say "Found a valid code signing identity named $PROD_CERT."
else
  warn "$PROD_CERT is not yet a valid code signing identity."
  _guide_trust "$PROD_CERT"
  pause "Press Enter once you've set it to Always Trust."
  _valid_identity "$PROD_CERT" && say "Identity is now valid." || warn "Still not valid; you can continue and fix it later."
fi

# ── Stage 4 ───────────────────────────────────────────────────────────────
stage "Point each configuration at its certificate"
say "Debug and Release include a gitignored local file at the end, so the"
say "committed project still signs ad-hoc for anyone who clones it."
cat > "$ROOT/Config/Debug.local.xcconfig" <<EOF
// Local signing identity, gitignored. See Config/Debug.local.xcconfig.example.
CODE_SIGN_IDENTITY = $DEV_CERT
EOF
cat > "$ROOT/Config/Release.local.xcconfig" <<EOF
// Local signing identity, gitignored. See Config/Release.local.xcconfig.example.
CODE_SIGN_IDENTITY = $PROD_CERT
EOF
note "wrote Config/Debug.local.xcconfig → $DEV_CERT"
note "wrote Config/Release.local.xcconfig → $PROD_CERT"
printf '\n'
note "Neither file is tracked by git."
pause "Press Enter to export production for CI."

# ── Stage 5 ───────────────────────────────────────────────────────────────
stage "Export production and store the repository secrets"
say "CI imports a password-protected copy of the production identity, so the"
say "app it builds carries the same identity as this Mac."
say ""
step "In Keychain Access, select the $PROD_CERT certificate."
step "Expand it and select the certificate and its private key together."
step "File > Export Items, File Format: Personal Information Exchange (.p12)."
step "Save it somewhere temporary and set a password when asked."
say ""
ask P12_PATH "Path to the exported .p12 (drag the file here, then Enter):"
P12_PATH="${P12_PATH//\\/}"
P12_PATH="${P12_PATH%\"}"; P12_PATH="${P12_PATH#\"}"
P12_PATH="${P12_PATH%\'}"; P12_PATH="${P12_PATH#\'}"
P12_PATH="${P12_PATH/#\~/$HOME}"
if [[ -f "$P12_PATH" ]]; then
  note "found $P12_PATH"
else
  warn "no file at $P12_PATH; set CERTIFICATE_P12_BASE64 by hand later"
fi
ask_secret CERTIFICATE_PASSWORD "Password you set on the .p12:"

KEYCHAIN_PASSWORD="$(openssl rand -base64 24)"
PROBE_OK=0
if [[ -f "$P12_PATH" && -n "$CERTIFICATE_PASSWORD" ]]; then
  note "Checking the .p12 imports the same way CI will..."
  PROBE_DIR="$(mktemp -d)"
  PROBE_KC="$PROBE_DIR/probe.keychain"
  if security create-keychain -p probe "$PROBE_KC" >/dev/null 2>&1 \
    && security import "$P12_PATH" -k "$PROBE_KC" -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign >/dev/null 2>&1 \
    && security find-identity -p codesigning "$PROBE_KC" > "$PROBE_DIR/ids" 2>/dev/null \
    && grep -qF "$PROD_CERT" "$PROBE_DIR/ids"; then
    PROBE_OK=1
    say "The .p12 and password import cleanly with a signing key."
  else
    warn "The .p12 did not import with a usable private key. Check the password,"
    warn "and re-export selecting the certificate and its private key together."
  fi
  security delete-keychain "$PROBE_KC" >/dev/null 2>&1 || true
  rm -rf "$PROBE_DIR"
else
  warn "Skipping the import check: need an existing .p12 and a non-empty password."
fi

if [[ "$PROBE_OK" == 1 ]]; then
  set_secret CERTIFICATE_P12_BASE64 "$(base64 -i "$P12_PATH" | tr -d '\n')"
  set_secret CERTIFICATE_PASSWORD "$CERTIFICATE_PASSWORD"
else
  SKIPPED+=("CERTIFICATE_P12_BASE64 and CERTIFICATE_PASSWORD (re-run after re-exporting)")
  warn "Left CERTIFICATE_P12_BASE64 and CERTIFICATE_PASSWORD unset."
fi
set_secret KEYCHAIN_PASSWORD "$KEYCHAIN_PASSWORD"
set_var SIGNING_IDENTITY "$PROD_CERT"
pause "Press Enter to back up the .p12."

# ── Stage 6 ───────────────────────────────────────────────────────────────
stage "Back up the production certificate"
say "Regenerating this certificate makes every recipient grant Input Monitoring"
say "again, so keep the .p12 somewhere you will still have it in ten years."
say ""
ask BACKUP_DIR "Backup folder [$HOME/Documents]:"
BACKUP_DIR="${BACKUP_DIR:-$HOME/Documents}"
BACKUP_DIR="${BACKUP_DIR/#\~/$HOME}"
mkdir -p "$BACKUP_DIR"
if [[ -f "$P12_PATH" ]]; then
  cp "$P12_PATH" "$BACKUP_DIR/$PROD_CERT.p12"
  say "Copied to $BACKUP_DIR/$PROD_CERT.p12"
  say "Keep the .p12 password with it, in your password manager."
else
  warn "No .p12 to copy; export it first and copy it by hand."
fi
pause "Press Enter to verify both channels."

# ── Stage 7 ───────────────────────────────────────────────────────────────
stage "Verify both channels sign with their certificate"
say "Building both configurations and reading back the signature authority."
say ""
for config in Debug Release; do
  log="$(mktemp)"
  if (cd "$ROOT" && xcodebuild build -scheme AngryKeyboard -configuration "$config" \
      -destination 'generic/platform=macOS' -derivedDataPath build) >"$log" 2>&1; then
    app="$ROOT/build/Build/Products/$config/AngryKeyboard.app"
    [[ "$config" == "Debug" ]] && app="$ROOT/build/Build/Products/Debug/AngryKeyboardDev.app"
    expected="$DEV_CERT"; [[ "$config" == "Release" ]] && expected="$PROD_CERT"
    sig="$(codesign -dv --verbose=2 "$app" 2>&1 || true)"
    if [[ -d "$app" ]] && grep -qF "$expected" <<< "$sig"; then
      say "$config ($expected): signature matches."
    else
      authority="$(grep -m1 Authority <<< "$sig" || echo 'ad-hoc or missing')"
      warn "$config expected $expected: unexpected authority ($authority)"
    fi
  else
    warn "$config build failed; see $log"
  fi
  rm -f "$log"
done

finish
