#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

# Sparkle's EdDSA key signs the update archive and feed. The public key ships
# in Config/Info.plist; the private key lives in the login Keychain, the
# SPARKLE_PRIVATE_KEY CI secret, and a backup beside the certificate's.
#
# Keep SPARKLE_VERSION in step with the Sparkle package version in the Xcode
# project (added by ticket 03).
SPARKLE_VERSION="${SPARKLE_VERSION:-2.10.0}"
SPARKLE_ACCOUNT="${SPARKLE_ACCOUNT:-angrykeyboard}"
SPARKLE_SECRET="SPARKLE_PRIVATE_KEY"
CACHE_DIR="$HOME/Library/Caches/AngryKeyboard/sparkle-$SPARKLE_VERSION"

# _find_sparkle_bin prints a directory holding Sparkle's tools, if one exists.
# Prefers an explicit override, then a resolved Swift package, then the cache.
_find_sparkle_bin() {
  local candidates=(
    "${SPARKLE_BIN:-}"
    "$ROOT/build/SourcePackages/artifacts/sparkle/Sparkle/bin"
    "$ROOT/.build/artifacts/sparkle/Sparkle/bin"
    "$CACHE_DIR/bin"
  )
  local dir
  for dir in "${candidates[@]}"; do
    [[ -n "$dir" && -x "$dir/generate_keys" ]] && { printf '%s' "$dir"; return 0; }
  done
  return 1
}

# _public_key prints the base64 public key for SPARKLE_ACCOUNT, or fails.
_public_key() {
  "$SPARKLE_BIN_DIR/generate_keys" --account "$SPARKLE_ACCOUNT" -p
}

banner "AngryKeyboard update signing key"

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "Check prerequisites"
say "This wizard creates the EdDSA keypair Sparkle trusts updates with, stores the"
say "private key as the $SPARKLE_SECRET CI secret, backs it up beside the"
say "certificate, and prints the public key the app carries in Config/Info.plist."
note "The private key never enters the repo, and this wizard edits no tracked file."
say ""
say "Checking tools..."
for tool in curl tar security; do
  if command -v "$tool" >/dev/null 2>&1; then
    note "found $tool"
  else
    warn "missing $tool, which later stages need"
  fi
done
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  note "gh is authenticated"
else
  warn "gh is missing or unauthenticated; the CI secret will be skipped, not printed"
fi
pause "Press Enter to fetch Sparkle's signing tools."

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "Fetch Sparkle's signing tools"
say "Sparkle ships generate_keys with its releases. We use a resolved Swift"
say "package if one is present, otherwise download Sparkle $SPARKLE_VERSION to a cache."
say ""
if SPARKLE_BIN_DIR="$(_find_sparkle_bin)"; then
  say "Using the tools already at $SPARKLE_BIN_DIR"
else
  note "Downloading Sparkle $SPARKLE_VERSION to $CACHE_DIR..."
  mkdir -p "$CACHE_DIR"
  tarball="$CACHE_DIR/Sparkle-$SPARKLE_VERSION.tar.xz"
  if [[ ! -f "$tarball" ]]; then
    curl -fL --retry 3 -o "$tarball" \
      "https://github.com/sparkle-project/Sparkle/releases/download/$SPARKLE_VERSION/Sparkle-$SPARKLE_VERSION.tar.xz"
  fi
  tar -xf "$tarball" -C "$CACHE_DIR"
  if [[ -x "$CACHE_DIR/bin/generate_keys" ]]; then
    SPARKLE_BIN_DIR="$CACHE_DIR/bin"
    say "Using the tools at $SPARKLE_BIN_DIR"
  else
    warn "Could not find generate_keys after extracting; check $CACHE_DIR"
    exit 1
  fi
fi
pause "Press Enter to look for an existing key."

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "Find or create the EdDSA signing key"
say "generate_keys keeps the private key in your login Keychain under the account"
say "'$SPARKLE_ACCOUNT'. It reuses an existing key and never overwrites one, so this"
say "wizard is safe to re-run."
say ""
if PUBLIC_KEY="$(_public_key 2>/dev/null)"; then
  say "Found an existing key. Its public key is:"
  note "$PUBLIC_KEY"
  note "This wizard reuses it. To start over, first delete the 'Private key for"
  note "signing Sparkle updates' item for account '$SPARKLE_ACCOUNT' in Keychain Access."
  pause "Press Enter to reuse this key."
else
  note "No key found for account '$SPARKLE_ACCOUNT'."
  say ""
  ask IMPORT_KEY_FILE "Path to an exported key to restore, or Enter to create a new one:"
  IMPORT_KEY_FILE="${IMPORT_KEY_FILE/#\~/$HOME}"
  if [[ -n "$IMPORT_KEY_FILE" && -f "$IMPORT_KEY_FILE" ]]; then
    say "Importing the key from $IMPORT_KEY_FILE..."
    "$SPARKLE_BIN_DIR/generate_keys" --account "$SPARKLE_ACCOUNT" -f "$IMPORT_KEY_FILE"
  else
    [[ -n "$IMPORT_KEY_FILE" ]] && warn "No file at $IMPORT_KEY_FILE; creating a new key instead."
    "$SPARKLE_BIN_DIR/generate_keys" --account "$SPARKLE_ACCOUNT"
  fi
  PUBLIC_KEY="$(_public_key)"
  say "Created a new key. Its public key is:"
  note "$PUBLIC_KEY"
fi
pause "Press Enter to store the private key as a CI secret."

# ── Stage 4 ───────────────────────────────────────────────────────────────
stage "Store the private key as the CI secret"
say "CI signs the feed with this key, piping it to the signing tool over stdin and"
say "never writing it to disk there."
say ""
EXPORT_DIR="$(mktemp -d)"
EXPORT_FILE="$EXPORT_DIR/sparkle-private-key"
"$SPARKLE_BIN_DIR/generate_keys" --account "$SPARKLE_ACCOUNT" -x "$EXPORT_FILE"
chmod 600 "$EXPORT_FILE"
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1 \
  && gh secret list 2>/dev/null | grep -q "^$SPARKLE_SECRET"; then
  warn "$SPARKLE_SECRET is already set; this overwrites it with this Mac's key."
  if confirm "Overwrite the $SPARKLE_SECRET secret?"; then
    set_secret "$SPARKLE_SECRET" "$(cat "$EXPORT_FILE")"
  else
    SKIPPED+=("GitHub secret $SPARKLE_SECRET (left unchanged)")
    warn "Left $SPARKLE_SECRET unchanged."
  fi
else
  set_secret "$SPARKLE_SECRET" "$(cat "$EXPORT_FILE")"
fi
pause "Press Enter to back up the private key."

# ── Stage 5 ───────────────────────────────────────────────────────────────
stage "Back up the private key"
say "Losing this key strands every installed app until users reinstall by hand, so"
say "keep it beside the production certificate's .p12 backup."
say ""
ask BACKUP_DIR "Backup folder [$HOME/Documents]:"
BACKUP_DIR="${BACKUP_DIR:-$HOME/Documents}"
BACKUP_DIR="${BACKUP_DIR/#\~/$HOME}"
mkdir -p "$BACKUP_DIR"
BACKUP_FILE="$BACKUP_DIR/AngryKeyboard-sparkle-ed25519-private-key.txt"
if [[ -f "$BACKUP_FILE" ]] && cmp -s "$EXPORT_FILE" "$BACKUP_FILE"; then
  say "The backup already matches this key: $BACKUP_FILE"
elif [[ -f "$BACKUP_FILE" ]]; then
  warn "A different backup already exists at $BACKUP_FILE."
  if confirm "Replace it with this key?"; then
    cp "$EXPORT_FILE" "$BACKUP_FILE"; chmod 600 "$BACKUP_FILE"
    say "Replaced $BACKUP_FILE"
  else
    SKIPPED+=("Update key backup ($BACKUP_FILE left unchanged)")
    warn "Left the existing backup unchanged."
  fi
else
  cp "$EXPORT_FILE" "$BACKUP_FILE"; chmod 600 "$BACKUP_FILE"
  say "Copied to $BACKUP_FILE"
fi
rm -rf "$EXPORT_DIR"
note "Record this folder beside the certificate backup in docs/signing.md."
pause "Press Enter to record the public key."

# ── Stage 6 ───────────────────────────────────────────────────────────────
stage "Record the public key in Info.plist"
say "The app carries the public key as SUPublicEDKey so it can verify updates."
note "This wizard leaves Config/Info.plist alone: no standard plist tool keeps its comments."
say ""
step "Set SUPublicEDKey in Config/Info.plist to:"
note "$PUBLIC_KEY"
note "Ticket 03 owns the rest of the plist contract and wires the app."

finish
