#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────
#
# Update verification wizard (ticket 07). This walks the manual end-to-end test
# on a real Mac: dispatch the rehearsal, install an older signed Release build,
# point it at the local feed over HTTP, drive a real Sparkle update, and record
# what survived. It writes no tracked file except the ticket record it appends
# at the end, which you commit yourself. It is safe to re-run: the values it
# captures persist under build/, which is gitignored.

TOTAL_STAGES=10

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

# The library defaulted ENV_FILE to the repo's .env. Keep captures under build/
# so re-runs resume and the working tree stays clean.
ENV_FILE="$ROOT/build/verify-update.env"
mkdir -p "$ROOT/build"
# Resume values captured by an earlier run so the wizard can be re-entered.
if [[ -f "$ENV_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$ENV_FILE"
fi

PROD_CERT="AngryKeyboard Production"
BUNDLE_ID="com.zzacong.AngryKeyboard"
REHEARSAL_WORKFLOW="dmg-rehearsal.yml"
# The ref the rehearsal runs from. GitHub runs the workflow version pushed on
# this ref, so it must be on origin before dispatch. Defaults to this branch.
REHEARSAL_REF="${REHEARSAL_REF:-$(git -C "$ROOT" rev-parse --abbrev-ref HEAD)}"
REHEARSAL_ARTIFACT="AngryKeyboard-dmg-rehearsal"
REHEARSAL_PAGE="https://github.com/zzacong/angry-keyboard/actions/workflows/$REHEARSAL_WORKFLOW"
TICKET="$ROOT/.scratch/autoupdate/issues/07-verify-an-update-on-a-real-mac.md"

OLD_BUILD_DIR="$ROOT/build/verify-old"
ARTIFACT_DIR="$ROOT/build/rehearsal"
PREFS_BEFORE="$ROOT/build/verify-update.prefs.before"
SERVER_LOG="$ROOT/build/verify-update.http.log"
SERVER_PID=""
GATEKEEPER_REPROMPT="no"
GATEKEEPER_DETAIL=""
INPUT_MONITORING_OK="unknown"
LOGIN_ITEM_OK="unknown"

# _gh_ok is true when gh is installed and authenticated.
_gh_ok() { command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; }

# _ref_pushed is true when REHEARSAL_REF exists on origin. workflow_dispatch runs
# the workflow version on that ref, so it has to be on GitHub first.
_ref_pushed() { git -C "$ROOT" ls-remote --exit-code --heads origin "$REHEARSAL_REF" >/dev/null 2>&1; }

# _quit_app stops a running production app so preferences and the feed override
# can be written without the app overwriting them on its way out.
_quit_app() {
  pkill -x AngryKeyboard >/dev/null 2>&1 || true
  sleep 1
}

# _server_stop shuts down the HTTP server if this run started one. Also runs on
# exit, so Ctrl-C does not leave a server behind.
_server_stop() {
  if [[ -n "$SERVER_PID" ]]; then
    kill "$SERVER_PID" >/dev/null 2>&1 || true
    wait "$SERVER_PID" 2>/dev/null || true
    SERVER_PID=""
  fi
}
trap _server_stop EXIT

banner "AngryKeyboard update verification"

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "Check prerequisites"
say "This wizard exercises a real Sparkle update on this Mac. It installs an"
say "older signed Release build, serves the rehearsal feed over HTTP, drives the"
say "update from the status menu, and records what survived."
say ""
warn "It installs an app, may replace one at the path you choose, asks macOS for"
warn "Input Monitoring, and registers a Login Item. Read each stage first."
say ""
say "Checking tools..."
for tool in xcodebuild gh git curl python3 ditto defaults security; do
  if command -v "$tool" >/dev/null 2>&1; then
    note "found $tool"
  else
    warn "missing $tool, which later stages need"
  fi
done

if _gh_ok; then
  note "gh is authenticated; the rehearsal is dispatched from here."
else
  warn "gh is missing or unauthenticated; you will drive the workflow by hand."
fi

if security find-identity -v -p codesigning 2>/dev/null | grep -qF "$PROD_CERT"; then
  say "Found the $PROD_CERT signing identity."
else
  warn "$PROD_CERT is not a valid code signing identity on this Mac."
  say "Run Scripts/setup-signing.sh first, then re-run this wizard."
  pause "Press Enter once the production identity exists (or Ctrl-C to stop)."
fi

if _ref_pushed; then
  note "Rehearsal ref: $REHEARSAL_REF (present on origin)."
else
  warn "Rehearsal ref '$REHEARSAL_REF' is not on origin."
  say "GitHub runs the workflow version pushed on that ref, so push it first:"
  step "git push -u origin $REHEARSAL_REF"
  pause "Press Enter once it is pushed (or Ctrl-C to stop)."
fi
say ""
note "Bundle id under test: $BUNDLE_ID (production)."
note "The installed build must already carry Sparkle: a pre-Sparkle install can"
note "never update itself. A local Release build from this tree does."
pause "Press Enter to dispatch the rehearsal."

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "Run the rehearsal workflow"
say "The dmg-rehearsal workflow builds a signed DMG and a signed feed with the"
say "release key and uploads them as one artifact. It publishes nothing."
say ""
RUN_ID=""
if _gh_ok; then
  open_url "$REHEARSAL_PAGE"
  if confirm "Dispatch $REHEARSAL_WORKFLOW on $REHEARSAL_REF now?"; then
    PREV_RUN_ID="$(gh run list --workflow "$REHEARSAL_WORKFLOW" --limit 1 --json databaseId --jq '.[0].databaseId' 2>/dev/null || true)"
    if gh workflow run "$REHEARSAL_WORKFLOW" --ref "$REHEARSAL_REF"; then
      say "Dispatched. Waiting for the run to register..."
      for _ in {1..30}; do
        RUN_ID="$(gh run list --workflow "$REHEARSAL_WORKFLOW" --limit 1 --json databaseId --jq '.[0].databaseId' 2>/dev/null || true)"
        if [[ -n "$RUN_ID" && "$RUN_ID" != "$PREV_RUN_ID" ]]; then break; fi
        RUN_ID=""
        sleep 1
      done
    else
      warn "Dispatch failed; run it from the Actions page instead."
    fi
  fi
else
  warn "Dispatch it by hand, then come back:"
  step "gh workflow run $REHEARSAL_WORKFLOW --ref $REHEARSAL_REF"
  pause "Press Enter once the run is visible on the Actions page."
fi

if [[ -n "$RUN_ID" ]]; then
  say "Watching run $RUN_ID to completion; this can take a few minutes..."
  if gh run watch "$RUN_ID" --exit-status >/dev/null 2>&1; then
    say "Run $RUN_ID finished successfully."
  else
    warn "Run $RUN_ID did not finish successfully. See $REHEARSAL_PAGE"
    confirm "Continue anyway?" || exit 1
  fi
  REHEARSAL_RUN_ID="$RUN_ID"
else
  ask REHEARSAL_RUN_ID "Rehearsal run id:"
fi

if [[ -n "${REHEARSAL_RUN_ID:-}" ]]; then
  write_env REHEARSAL_RUN_ID "$REHEARSAL_RUN_ID"
  note "Run URL: https://github.com/zzacong/angry-keyboard/actions/runs/$REHEARSAL_RUN_ID"
else
  warn "No run id recorded; later stages will ask for one."
fi
pause "Press Enter to download the artifact."

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "Download the artifact and read the feed version"
say "The artifact holds the signed feed, the DMG it names, and the checksum as"
say "flat siblings. The feed's sparkle:version is the build number an installed"
say "build must beat, so we read what 'newer' means here."
say ""
if [[ -z "${REHEARSAL_RUN_ID:-}" ]]; then
  ask REHEARSAL_RUN_ID "Rehearsal run id:"
fi

DEFAULT_ARTIFACT_DIR="$ARTIFACT_DIR"
ask ARTIFACT_DIR "Artifact directory (default $DEFAULT_ARTIFACT_DIR):"
ARTIFACT_DIR="${ARTIFACT_DIR:-$DEFAULT_ARTIFACT_DIR}"
ARTIFACT_DIR="${ARTIFACT_DIR/#\~/$HOME}"

if _gh_ok && [[ -n "${REHEARSAL_RUN_ID:-}" ]]; then
  case "$ARTIFACT_DIR" in
    "$ROOT"/build/*) rm -rf "$ARTIFACT_DIR" ;;
    *) if [[ -d "$ARTIFACT_DIR" ]]; then warn "Leaving existing files in $ARTIFACT_DIR in place."; fi ;;
  esac
  mkdir -p "$ARTIFACT_DIR"
  if gh run download "$REHEARSAL_RUN_ID" -n "$REHEARSAL_ARTIFACT" -D "$ARTIFACT_DIR"; then
    say "Downloaded to $ARTIFACT_DIR"
  else
    warn "Download failed; is run $REHEARSAL_RUN_ID finished with its artifact ready?"
  fi
else
  warn "gh is not ready; download by hand into $ARTIFACT_DIR:"
  step "gh run download $REHEARSAL_RUN_ID -n $REHEARSAL_ARTIFACT -D $ARTIFACT_DIR"
  pause "Press Enter once the three files are in place."
fi

for f in appcast.xml AngryKeyboard.dmg AngryKeyboard.dmg.sha256; do
  if [[ -f "$ARTIFACT_DIR/$f" ]]; then
    note "found $f"
  else
    warn "missing $f in $ARTIFACT_DIR"
  fi
done

APPCAST="$ARTIFACT_DIR/appcast.xml"
FEED_VERSION=""
FEED_SHORT=""
if [[ -f "$APPCAST" ]]; then
  FEED_VERSION="$(grep -o 'sparkle:version="[0-9][^"]*"' "$APPCAST" | head -n1 | sed -E 's/.*"([^"]*)"/\1/' || true)"
  FEED_SHORT="$(grep -o 'sparkle:shortVersionString="[^"]*"' "$APPCAST" | head -n1 | sed -E 's/.*"([^"]*)"/\1/' || true)"
  say "Feed advertises version $FEED_VERSION (marketing $FEED_SHORT)."
  if [[ -n "$FEED_VERSION" ]]; then REHEARSAL_VERSION="$FEED_VERSION"; write_env REHEARSAL_VERSION "$FEED_VERSION"; fi
  if [[ -n "$FEED_SHORT" ]]; then REHEARSAL_MARKETING="$FEED_SHORT"; write_env REHEARSAL_MARKETING "$FEED_SHORT"; fi
else
  warn "No appcast.xml; cannot read the feed version."
fi
pause "Press Enter to build the older app."

# ── Stage 4 ───────────────────────────────────────────────────────────────
stage "Build and install the older production build"
say "We build a Release app whose CFBundleVersion is below the feed's"
say "sparkle:version, signed with $PROD_CERT so the Input Monitoring grant under"
say "test is the production one."
say ""
if ! [[ "${FEED_VERSION:-}" =~ ^[0-9]+$ ]]; then
  warn "No numeric feed version in hand; enter the build number the feed advertises."
  ask FEED_VERSION "Feed build number (sparkle:version):"
fi
DEFAULT_OLD_BUILD=$(( ${FEED_VERSION:-1} - 1 ))
if (( DEFAULT_OLD_BUILD < 1 )); then
  warn "The feed version is ${FEED_VERSION:-?}; no lower positive build number exists."
  warn "Run the rehearsal again later (run numbers only rise) or enter a value by hand."
fi
ask OLD_BUILD "Older build number [$DEFAULT_OLD_BUILD]:"
OLD_BUILD="${OLD_BUILD:-$DEFAULT_OLD_BUILD}"
ask OLD_MARKETING "Older marketing version [0.0.1]:"
OLD_MARKETING="${OLD_MARKETING:-0.0.1}"

if ! [[ "$OLD_BUILD" =~ ^[0-9]+$ ]]; then
  warn "Build number must be numeric: $OLD_BUILD"
  exit 1
fi
if [[ "${FEED_VERSION:-}" =~ ^[0-9]+$ ]] && (( OLD_BUILD >= FEED_VERSION )); then
  warn "Build $OLD_BUILD is not below the feed's $FEED_VERSION; Sparkle sees nothing new."
  confirm "Continue anyway?" || exit 1
fi

say "Building Release ($OLD_MARKETING / $OLD_BUILD)..."
BUILD_LOG="$ROOT/build/verify-old-build.log"
if xcodebuild -project AngryKeyboard.xcodeproj -scheme AngryKeyboard -configuration Release \
  -destination 'generic/platform=macOS' -derivedDataPath "$OLD_BUILD_DIR" \
  MARKETING_VERSION="$OLD_MARKETING" CURRENT_PROJECT_VERSION="$OLD_BUILD" \
  CODE_SIGN_STYLE=Manual CODE_SIGN_IDENTITY="$PROD_CERT" build >"$BUILD_LOG" 2>&1; then
  say "Build finished."
else
  warn "Build failed; see $BUILD_LOG"
  exit 1
fi

OLD_APP="$OLD_BUILD_DIR/Build/Products/Release/AngryKeyboard.app"
if [[ -d "$OLD_APP" ]] && codesign -dv --verbose=2 "$OLD_APP" 2>&1 | grep -qF "Authority=$PROD_CERT"; then
  say "Built app is signed by $PROD_CERT."
else
  warn "$OLD_APP is missing or not signed by $PROD_CERT; the grant is not under test."
fi
note "Built app reports CFBundleVersion $(/usr/libexec/PlistBuddy -c 'Print :CFBundleVersion' "$OLD_APP/Contents/Info.plist" 2>/dev/null || echo '?')."

DEFAULT_INSTALL="$HOME/Applications/AngryKeyboard.app"
ask INSTALL_APP "Install to (default $DEFAULT_INSTALL):"
INSTALL_APP="${INSTALL_APP:-$DEFAULT_INSTALL}"
INSTALL_APP="${INSTALL_APP/#\~/$HOME}"
if [[ "${INSTALL_APP##*/}" != *.app ]]; then
  warn "Install path must end in .app: $INSTALL_APP"
  exit 1
fi

if [[ -e "$INSTALL_APP" ]]; then
  warn "Something already exists at $INSTALL_APP."
  confirm "Replace it with the older test build?" || { say "Stopped before replacing anything."; exit 0; }
  _quit_app
  rm -rf "$INSTALL_APP"
fi
mkdir -p "$(dirname "$INSTALL_APP")"
if ditto "$OLD_APP" "$INSTALL_APP"; then
  say "Installed to $INSTALL_APP."
else
  warn "Could not install to $INSTALL_APP."
  exit 1
fi
open "$INSTALL_APP" >/dev/null 2>&1 || warn "Open $INSTALL_APP from Finder."
pause "Press Enter once the older build is running from its menu bar icon."

# ── Stage 5 ───────────────────────────────────────────────────────────────
stage "Establish the baseline"
say "Make the state we expect to survive deliberately distinctive, and confirm"
say "Input Monitoring already works, so the update has something to preserve."
say ""
open_url "x-apple.systempreferences:com.apple.preference.security?Privacy_ListenEvent"
step "In the app's menu, confirm the top line reads 'Input Monitoring: Granted'."
step "If it is not granted, turn AngryKeyboard on here, then quit and reopen the app."
step "Type in any text field and confirm you hear a sound."
pause "Press Enter once Input Monitoring is granted and sound plays."

say ""
say "Setting distinctive preferences: volume 0.42, Overlap Sounds on, unmuted."
_quit_app
defaults write "$BUNDLE_ID" volume -float 0.42
defaults write "$BUNDLE_ID" playbackMode -string overlap
defaults write "$BUNDLE_ID" muted -bool false
defaults read "$BUNDLE_ID" > "$PREFS_BEFORE" 2>/dev/null || true
say "Saved the pre-update preferences to $PREFS_BEFORE"
open "$INSTALL_APP" >/dev/null 2>&1 || warn "Open $INSTALL_APP from Finder."

step "In the app's menu, turn Launch at Login ON."
step "Confirm Overlap Sounds is ticked and sound still plays."
pause "Press Enter once the baseline is set (granted, sound, Launch at Login on)."

# ── Stage 6 ───────────────────────────────────────────────────────────────
stage "Serve the feed and point the app at it"
say "Sparkle resolves the feed's relative enclosure against the feed's own URL,"
say "so the feed and the DMG must sit under the same HTTP root."
say ""
DEFAULT_PORT="${PORT:-8000}"
ask PORT "Local port (default $DEFAULT_PORT):"
PORT="${PORT:-$DEFAULT_PORT}"

if curl -fsS "http://localhost:$PORT/appcast.xml" >/dev/null 2>&1; then
  warn "Something is already serving on port $PORT."
  confirm "Use it as the feed?" || exit 1
else
  say "Starting python3 -m http.server on port $PORT from $ARTIFACT_DIR ..."
  nohup python3 -m http.server "$PORT" --directory "$ARTIFACT_DIR" >"$SERVER_LOG" 2>&1 &
  SERVER_PID=$!
  server_ok=0
  for _ in {1..40}; do
    if curl -fsS "http://localhost:$PORT/appcast.xml" >/dev/null 2>&1; then server_ok=1; break; fi
    sleep 0.25
  done
  if (( server_ok )); then
    say "Server is up (pid $SERVER_PID)."
  else
    warn "Server did not answer on port $PORT; see $SERVER_LOG"
  fi
fi
if curl -fsS "http://localhost:$PORT/appcast.xml" 2>/dev/null | grep -q 'AngryKeyboard.dmg'; then
  say "The feed names AngryKeyboard.dmg under this root."
else
  warn "The feed does not name AngryKeyboard.dmg; check the server root."
fi

say ""
say "Sparkle reads a SUFeedURL user default in preference to Info.plist, which is"
say "how the installed app is pointed at this local feed."
warn "The feed is plain HTTP on localhost. Sparkle logs an ATS warning and"
warn "continues; that warning is expected and is not a failure."
_quit_app
defaults write "$BUNDLE_ID" SUFeedURL "http://localhost:$PORT/appcast.xml"
say "Set SUFeedURL for $BUNDLE_ID to http://localhost:$PORT/appcast.xml"
open "$INSTALL_APP" >/dev/null 2>&1 || warn "Open $INSTALL_APP from Finder."
pause "Press Enter to trigger the update."

# ── Stage 7 ───────────────────────────────────────────────────────────────
stage "Trigger the update and confirm the relaunch"
say "This is the test. In the app's menu bar:"
step "Click the keyboard icon."
step "Choose 'Check for Updates…'."
step "When Sparkle offers the newer version, click Install (or Update)."
step "Let it download, verify, install, and relaunch on its own."
say ""
say "Sparkle quits the app, replaces it where it sits, and relaunches the new one."
pause "Press Enter once the app has relaunched."

if [[ -n "${REHEARSAL_VERSION:-}" && -f "$INSTALL_APP/Contents/Info.plist" ]]; then
  new_version="$(/usr/libexec/PlistBuddy -c 'Print :CFBundleVersion' "$INSTALL_APP/Contents/Info.plist" 2>/dev/null || true)"
  new_short="$(/usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' "$INSTALL_APP/Contents/Info.plist" 2>/dev/null || true)"
  say "Installed bundle now reports version $new_version (marketing $new_short)."
  if [[ "$new_version" == "$REHEARSAL_VERSION" ]]; then
    say "That matches the feed's sparkle:version $REHEARSAL_VERSION."
  else
    warn "Expected $REHEARSAL_VERSION; the bundle still reports $new_version."
    warn "The update may not have installed. Retry 'Check for Updates…'."
    confirm "Continue after the update installed?" || exit 1
  fi
else
  warn "Could not read the installed version; confirm it from About."
fi
if pgrep -x AngryKeyboard >/dev/null 2>&1; then
  say "The updated app is running."
else
  warn "The updated app does not look running; click its menu bar icon to open it."
fi
pause "Press Enter to check what survived."

# ── Stage 8 ───────────────────────────────────────────────────────────────
stage "Verify what survived"
say "Check each item against the baseline. Preferences are read back for you; the"
say "rest are things only you can see."
say ""
say "1. Input Monitoring"
step "Type in any text field: sound still plays."
step "The menu still reads 'Input Monitoring: Granted'."
if confirm "Did sound keep working with no re-approval?"; then
  INPUT_MONITORING_OK="yes"
else
  INPUT_MONITORING_OK="no"
  warn "Input Monitoring did not survive. This is a failure to record."
fi

say ""
say "2. Preferences and volume"
after_volume="$(defaults read "$BUNDLE_ID" volume 2>/dev/null || true)"
after_mode="$(defaults read "$BUNDLE_ID" playbackMode 2>/dev/null || true)"
after_muted="$(defaults read "$BUNDLE_ID" muted 2>/dev/null || true)"
say "volume now $after_volume (expected 0.42)"
say "playbackMode now $after_mode (expected overlap)"
say "muted now $after_muted (expected 0)"
if [[ "$after_volume" == "0.42" && "$after_mode" == "overlap" ]]; then
  say "Preferences survived."
else
  warn "Preferences differ from the baseline; record the actual values."
fi

say ""
say "3. Sound pack"
note "v1 ships one pack, 'Angry Keyboard', so there is nothing to switch. Its"
note "sounds still playing is the observable meaning of 'survived' here."
confirm "Do the same key sounds still play?" || warn "Sound pack sounds changed; record it."

say ""
say "4. Login Item"
open_url "x-apple.systempreferences:com.apple.LoginItems-Settings.extension"
step "In the app's menu, Launch at Login is still ticked."
step "System Settings > General > Login Items still lists AngryKeyboard."
if confirm "Did the Login Item survive?"; then
  LOGIN_ITEM_OK="yes"
else
  LOGIN_ITEM_OK="no"
  warn "Login Item did not survive. This is a failure to record."
fi
pause "Press Enter to record the result."

# ── Stage 9 ───────────────────────────────────────────────────────────────
stage "Record the result"
say "The ticket asks one explicit question about Gatekeeper. Answer it honestly:"
say "a re-prompt after an update means ADR 0010 is wrong about quarantine and it"
say "must be updated too."
say ""
if confirm "Did macOS show a Gatekeeper prompt ('cannot be verified' / Open Anyway) when the updated app launched?"; then
  GATEKEEPER_REPROMPT="yes"
  ask GATEKEEPER_DETAIL "What did you see, and what did you have to click?"
  say ""
  warn "Failure branch: the update re-prompted."
  warn "Open docs/adr/0010-in-app-updates-with-sparkle.md and record the observed"
  warn "behaviour before committing the ticket record."
  pause "Press Enter once you have noted it (or Ctrl-C to stop and keep the app)."
else
  GATEKEEPER_REPROMPT="no"
  say "No re-prompt on the updated launch, as ADR 0010 expects."
fi

TODAY="$(date '+%Y-%m-%d')"
MACOS="$(sw_vers -productVersion 2>/dev/null || echo unknown)"
ARCH="$(uname -m)"
RUN_URL="https://github.com/zzacong/angry-keyboard/actions/runs/${REHEARSAL_RUN_ID:-unknown}"

say ""
say "──────────────────────────────────────────────────────────────"
say "Update verification summary"
say "  Date:             $TODAY (macOS $MACOS, $ARCH)"
say "  Older build:      $OLD_MARKETING ($OLD_BUILD)"
say "  Updated to:       ${REHEARSAL_MARKETING:-?} (${REHEARSAL_VERSION:-?})"
say "  Rehearsal run:    ${REHEARSAL_RUN_ID:-unknown} — $RUN_URL"
say "  Input Monitoring: $INPUT_MONITORING_OK"
say "  Preferences:      volume=$after_volume playbackMode=$after_mode muted=$after_muted"
say "  Login Item:       $LOGIN_ITEM_OK"
say "  Gatekeeper:       re-prompt=$GATEKEEPER_REPROMPT${GATEKEEPER_DETAIL:+ — $GATEKEEPER_DETAIL}"
say "──────────────────────────────────────────────────────────────"

if [[ -f "$TICKET" ]]; then
  {
    grep -q '^## Comments$' "$TICKET" || printf '\n## Comments\n'
    printf '\n'
    printf -- '- %s — human run of `Scripts/verify-update.sh` on macOS %s (%s).\n' "$TODAY" "$MACOS" "$ARCH"
    printf '  An older Release build %s (%s) updated to the rehearsal build %s (%s)\n' \
      "$OLD_MARKETING" "$OLD_BUILD" "${REHEARSAL_MARKETING:-?}" "${REHEARSAL_VERSION:-?}"
    printf '  from rehearsal run %s (%s), relaunched, and reported:\n' "${REHEARSAL_RUN_ID:-unknown}" "$RUN_URL"
    printf -- '  - Input Monitoring and sound: %s\n' "$INPUT_MONITORING_OK"
    printf -- '  - Preferences: volume=%s, playbackMode=%s, muted=%s\n' "$after_volume" "$after_mode" "$after_muted"
    printf -- '  - Login Item: %s\n' "$LOGIN_ITEM_OK"
    if [[ "$GATEKEEPER_REPROMPT" == "yes" ]]; then
      printf -- '  - Gatekeeper: RE-PROMPTED after the update — %s.\n' "${GATEKEEPER_DETAIL:-behaviour to describe}"
      printf -- '    ADR 0010 still needs updating to record this.\n'
    else
      printf -- '  - Gatekeeper: no re-prompt on the updated launch.\n'
    fi
  } >> "$TICKET"
  say "Appended the run record to $TICKET"
  say ""
  say "Commit it when you are ready:"
  step "git add '$TICKET' && git commit -m 'docs(app): record the real-Mac update verification'"
else
  warn "Ticket not found at $TICKET; keep the summary above."
fi
pause "Press Enter to clean up."

# ── Stage 10 ──────────────────────────────────────────────────────────────
stage "Clean up"
say "Removing the local feed override so the app goes back to the release feed."
if defaults read "$BUNDLE_ID" SUFeedURL >/dev/null 2>&1; then
  defaults delete "$BUNDLE_ID" SUFeedURL
  say "Deleted the SUFeedURL override."
else
  say "No SUFeedURL override was set."
fi
_server_stop
say "Stopped the local HTTP server."

if [[ -e "$INSTALL_APP" ]]; then
  warn "The test install is still at $INSTALL_APP."
  note "Its Input Monitoring grant and Login Item are shared with any other copy of"
  note "the $BUNDLE_ID app, since macOS keys both to the bundle id."
  step "If you are removing it, first turn Launch at Login OFF from its menu."
  if confirm "Quit and remove the test install now?"; then
    _quit_app
    rm -rf "$INSTALL_APP"
    say "Removed $INSTALL_APP."
  else
    say "Left $INSTALL_APP in place."
  fi
fi

note "The rehearsal artifact stays at $ARTIFACT_DIR; delete it when you are done."
finish
