import * as stylex from "@stylexjs/stylex";
import { tokens } from "@/styles/tokens.stylex";

// The live deck: the taped card's board, its status lights and its controls.
// The script in lib/deck.ts swaps classes for runtime state, including armed,
// hit, muted, and tried key groups.
const flashFade = stylex.keyframes({
  from: { opacity: 0.9 },
  to: { opacity: 0 },
});

const pop = stylex.keyframes({
  from: { opacity: 0, transform: "translateY(-3px)" },
  to: { opacity: 1, transform: "none" },
});

const keyHintJump = stylex.keyframes({
  "0%": {
    backgroundColor: "transparent",
    color: tokens.inkSoftest,
    transform: "translateY(0) scale(1)",
  },
  "20%": {
    backgroundColor: tokens.green,
    color: tokens.card,
    transform: "translateY(-0.45em) scale(1.12)",
  },
  "43%": {
    backgroundColor: tokens.green,
    color: tokens.card,
    transform: "translateY(0) scale(1)",
  },
  "60%": {
    backgroundColor: "transparent",
    color: tokens.inkSoftest,
    transform: "none",
  },
  "72%": {
    backgroundColor: tokens.noteGreen,
    color: tokens.green,
    transform: "none",
  },
  to: {
    backgroundColor: tokens.noteGreen,
    color: tokens.green,
    transform: "none",
  },
});

export const styles = stylex.create({
  bar: {
    gap: "1rem",
    paddingBlock: "0.7rem",
    paddingInline: "0.9rem",
    alignItems: "center",
    backgroundColor: tokens.cardBar,
    color: tokens.inkSoft,
    display: "flex",
    fontFamily: tokens.fontMono,
    fontSize: "11.5px",
    justifyContent: "space-between",
    letterSpacing: "0.04em",
    borderBottomColor: tokens.edge,
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
  },
  card: {
    borderColor: tokens.ink,
    borderRadius: "2px",
    borderStyle: "solid",
    borderWidth: "1.5px",
    paddingBlock: "1rem",
    paddingInline: "1rem",
    backgroundColor: tokens.card,
    boxShadow: "5px 7px 0 rgba(27, 23, 18, 0.22)",
  },
  chip: {
    borderColor: tokens.edge,
    borderRadius: "4px",
    borderStyle: "solid",
    borderWidth: "1px",
    paddingBlock: "0.15em",
    paddingInline: "0.45em",
    animationDuration: "250ms",
    animationName: pop,
    animationTimingFunction: "ease",
    color: tokens.inkSoft,
    fontFamily: tokens.fontMono,
    fontSize: "10.5px",
  },
  countNum: {
    color: tokens.ink,
    fontWeight: 600,
  },
  ctl: {
    gap: "0.45rem",
    alignItems: "center",
    display: "flex",
  },
  demo: {
    borderColor: tokens.ink,
    borderRadius: "2px",
    borderStyle: "solid",
    borderWidth: "1.5px",
    overflow: "hidden",
    backgroundColor: tokens.card,
    position: "relative",
  },
  dot: {
    borderRadius: "50%",
    backgroundColor: tokens.inkSoftest,
    transitionDuration: "200ms",
    transitionProperty: "background-color, box-shadow",
    height: "9px",
    width: "9px",
  },
  dotLive: {
    backgroundColor: tokens.red,
    boxShadow: "0 0 0 3px rgba(200, 40, 28, 0.18)",
  },
  flash: {
    backgroundImage:
      "radial-gradient(60% 60% at 18% 12%, rgba(200, 40, 28, 0.22), rgba(200, 40, 28, 0.1) 40%, transparent 70%)",
    opacity: 0,
    pointerEvents: "none",
    position: "absolute",
    zIndex: 2,
    bottom: 0,
    left: 0,
    right: 0,
    top: 0,
  },
  flashHit: {
    animationDuration: "220ms",
    animationName: flashFade,
    animationTimingFunction: "ease-out",
  },
  editor: {
    position: "relative",
  },
  guide: {
    paddingInline: "1rem",
    display: "grid",
    justifyItems: "center",
    pointerEvents: "none",
    position: "absolute",
    zIndex: 3,
    bottom: "0.65rem",
    left: 0,
    right: 0,
  },
  guideLine: {
    marginBlock: 0,
    color: tokens.inkSoftest,
    fontFamily: tokens.fontHand,
    fontSize: "clamp(1.1rem, 2vw, 1.5rem)",
    lineHeight: 1.2,
    textAlign: "center",
  },
  guidePart: {
    display: "inline",
  },
  guideToken: {
    borderRadius: "2px",
    paddingInline: "0.08em",
    color: tokens.inkSoftest,
    display: "inline-block",
    whiteSpace: "nowrap",
  },
  guideTokenHit: {
    animationDuration: {
      default: "720ms",
      "@media (prefers-reduced-motion: reduce)": "1ms",
    },
    animationName: keyHintJump,
    animationTimingFunction: "cubic-bezier(0.2, 0.8, 0.2, 1)",
  },
  guideTokenTried: {
    backgroundColor: tokens.noteGreen,
    color: tokens.green,
  },
  grenade: {
    transform: "rotate(13deg)",
    right: "-150px",
    top: "-48px",
    width: "80px",
  },
  hazard: {
    transform: "rotate(14deg)",
    left: "44%",
    top: "-96px",
    width: "82px",
  },
  hint: {
    color: tokens.blue,
    fontFamily: tokens.fontHand,
    fontSize: "1.4rem",
    transform: "rotate(-0.6deg)",
    marginBottom: 0,
    marginTop: "0.7rem",
  },
  foot: {
    paddingBlock: "0.7rem",
    paddingInline: "0.9rem",
    alignItems: "center",
    color: tokens.inkSoft,
    columnGap: "1rem",
    display: "flex",
    flexWrap: "wrap",
    fontFamily: tokens.fontMono,
    fontSize: "11.5px",
    rowGap: "0.7rem",
    borderTopColor: tokens.edge,
    borderTopStyle: "solid",
    borderTopWidth: "1px",
  },
  last: {
    color: tokens.ink,
    fontWeight: 500,
  },
  lastSound: {
    color: tokens.red,
    fontWeight: 600,
  },
  log: {
    gap: "0.3rem",
    display: "flex",
    flexWrap: "wrap",
    marginLeft: "auto",
  },
  mute: {
    borderColor: tokens.edgeStrong,
    borderRadius: "5px",
    borderStyle: "solid",
    borderWidth: "1px",
    paddingBlock: "0.25em",
    paddingInline: "0.55em",
    backgroundColor: "transparent",
    color: tokens.inkSoft,
    cursor: "pointer",
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    letterSpacing: "0.04em",
  },
  muteOn: {
    borderColor: tokens.red,
    backgroundColor: tokens.red,
    color: tokens.card,
  },
  paste: {
    position: "relative",
    transform: "rotate(-0.7deg)",
    marginTop: "1.8rem",
  },
  pow: {
    transform: "rotate(-14deg)",
    left: "-150px",
    top: "-62px",
    width: "124px",
  },
  status: {
    gap: "0.5rem",
    alignItems: "center",
    display: "flex",
  },
  statusText: {
    color: tokens.inkSoft,
  },
  statusTextLive: {
    color: tokens.ink,
  },
  surface: {
    borderWidth: 0,
    paddingInline: "1.25rem",
    backgroundColor: tokens.card,
    caretColor: tokens.red,
    color: tokens.ink,
    display: "block",
    fontFamily: tokens.fontMono,
    fontSize: "clamp(15px, 1.6vw, 18px)",
    lineHeight: 1.75,
    outlineStyle: "none",
    outlineWidth: 0,
    paddingBlockEnd: {
      default: "3rem",
      "@media (max-width: 620px)": "4.25rem",
    },
    paddingBlockStart: "1.2rem",
    resize: "none",
    // Reserve bottom space for the floating hint, including on narrow screens.
    minHeight: "224px",
    width: "100%",
    "::placeholder": { color: tokens.inkSoftest },
  },
  visuallyHidden: {
    overflow: "hidden",
    clip: "rect(0, 0, 0, 0)",
    clipPath: "inset(50%)",
    position: "absolute",
    whiteSpace: "nowrap",
    height: "1px",
    width: "1px",
  },
  volume: {
    accentColor: tokens.red,
    width: "88px",
  },
});
