import * as stylex from "@stylexjs/stylex";
import { tokens } from "@/styles/tokens.stylex";

export const styles = stylex.create({
  box: {
    borderColor: tokens.ink,
    borderStyle: "solid",
    borderWidth: "1.5px",
    backgroundColor: tokens.red,
    flexShrink: 0,
    position: "relative",
    height: "16px",
    width: "16px",
    "::after": {
      content: '""',
      position: "absolute",
      transform: "rotate(40deg)",
      borderBottomColor: tokens.card,
      borderBottomStyle: "solid",
      borderBottomWidth: "2px",
      borderRightColor: tokens.card,
      borderRightStyle: "solid",
      borderRightWidth: "2px",
      height: "9px",
      left: "4px",
      top: "1px",
      width: "5px",
    },
  },
  crate: {
    transform: "rotate(-5deg)",
    left: "-10px",
    top: "110px",
    width: "158px",
  },
  fist: {
    transform: "rotate(10deg)",
    left: "170px",
    top: "146px",
    width: "94px",
  },
  item: {
    gap: "0.75rem",
    paddingBlock: "0.7rem",
    alignItems: "center",
    display: "flex",
    borderBottomColor: "rgba(27, 23, 18, 0.28)",
    borderBottomStyle: "solid",
    borderBottomWidth: "1.5px",
  },
  list: {
    margin: 0,
    padding: 0,
    listStyleType: "none",
    borderTopColor: tokens.ink,
    borderTopStyle: "solid",
    borderTopWidth: "1.5px",
  },
  section: {
    gap: "clamp(2rem, 6vw, 4rem)",
    alignItems: "start",
    display: "grid",
    gridTemplateColumns: {
      default: "1fr 1.35fr",
      "@media (max-width: 980px)": "1fr",
    },
    position: "relative",
    marginTop: "3.6rem",
  },
  sound: {
    color: tokens.red,
    fontFamily: tokens.fontHand,
    fontSize: "1.3rem",
    marginLeft: "auto",
  },
  sub: {
    margin: 0,
    color: tokens.inkSoft,
    fontSize: "1rem",
    maxWidth: "30ch",
  },
  title: {
    fontFamily: tokens.fontHead,
    fontSize: "clamp(1.5rem, 3.2vw, 2.3rem)",
    fontWeight: 800,
    letterSpacing: "-0.02em",
    lineHeight: 1.02,
    marginBottom: "0.5rem",
    marginTop: 0,
  },
});
